// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1Tn9UbGXG0LgXOppcWOwA-uZU5WWUQY',
    appId: '1:688610915126:web:b72d271397f65a0dfe7997',
    messagingSenderId: '688610915126',
    projectId: 'commentsapp-4a873',
    authDomain: 'commentsapp-4a873.firebaseapp.com',
    storageBucket: 'commentsapp-4a873.appspot.com',
    measurementId: 'G-E3JM50LK84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1NFgEuCrMPO5XWWsLdc43nZCyjSDbuHs',
    appId: '1:688610915126:android:480a20af475a29aefe7997',
    messagingSenderId: '688610915126',
    projectId: 'commentsapp-4a873',
    storageBucket: 'commentsapp-4a873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFc11Vq_Mpx6TAb90-URtmLwZDsbuzdU',
    appId: '1:688610915126:ios:a49bf916e8fa78fefe7997',
    messagingSenderId: '688610915126',
    projectId: 'commentsapp-4a873',
    storageBucket: 'commentsapp-4a873.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFc11Vq_Mpx6TAb90-URtmLwZDsbuzdU',
    appId: '1:688610915126:ios:a49bf916e8fa78fefe7997',
    messagingSenderId: '688610915126',
    projectId: 'commentsapp-4a873',
    storageBucket: 'commentsapp-4a873.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1Tn9UbGXG0LgXOppcWOwA-uZU5WWUQY',
    appId: '1:688610915126:web:67452b3c7d748861fe7997',
    messagingSenderId: '688610915126',
    projectId: 'commentsapp-4a873',
    authDomain: 'commentsapp-4a873.firebaseapp.com',
    storageBucket: 'commentsapp-4a873.appspot.com',
    measurementId: 'G-Y2MEZT8YWV',
  );
}
